application: apt-miniproject-1078
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /
  script: connexus.app
- url: /tasks/update_trending
  script: connexus.app
  login: admin
- url: /tasks/email_trending
  script: connexus.app
  login: admin
- url: /dropzone
  static_dir: dropzone
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /fonts
  static_dir: fonts
- url: /.*
  script: connexus.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: PIL
  version: latest
